name: Build and Push Docker Image

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t 1giodev/sendmailapi:latest .

    - name: Push Docker image to Docker Hub
      run: docker push 1giodev/sendmailapi:latest
